weights:
  face_match: 0.35
  liveness_active: 0.20
  liveness_passive: 0.15 # if not provided by LLM, set default 0.70
  av_sync: 0.15
  audio_antispoof: 0.10
  ocr_consistency: 0.05

thresholds:
  verified: 0.75
  review: 0.60
